import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Home, Layers, ArrowLeftRight, TrendingUp, ShieldCheck, CheckCircle2, ArrowRight, Sparkles } from 'lucide-react';

export default function HowItWorks() {
  const [activeTab, setActiveTab] = useState<'properties' | 'staking' | 'p2p' | 'invest'>('properties');

  const products = {
    properties: {
      title: 'Real Estate Properties',
      tagline: 'Fractional Real Estate with Consistent Rental Distributions',
      badge: '9.0% – 14.5% Annual Yield',
      desc: 'Invest in premium vetted real estate properties worldwide starting from just $500. Receive recurring rental dividends and long-term capital appreciation without managing physical tenants.',
      steps: [
        {
          num: '1',
          title: 'Browse Verified Listings',
          desc: 'Explore institutional-grade residential and commercial real estate properties with full title documentation, valuation reports, and verified legal registries.'
        },
        {
          num: '2',
          title: 'Purchase Fractional Shares',
          desc: 'Select how many units or shares you wish to own. Pay securely using your RPM liquid wallet balance or USDT.'
        },
        {
          num: '3',
          title: 'Collect Rental Dividends',
          desc: 'Rental revenue generated by tenants is distributed automatically to your wallet. You can liquidate or sell your shares at any time.'
        }
      ],
      highlights: [
        'Legally documented fractional deeds',
        'Direct automated rental distribution',
        'Zero property maintenance duties',
        'Independent third-party property appraisals'
      ],
      cta: 'Explore Properties',
      link: '/app/properties',
      color: 'amber'
    },
    staking: {
      title: 'Locked Savings (Staking)',
      tagline: 'Guaranteed Principal with High Fixed Daily APY',
      badge: 'Up to 18% APY',
      desc: 'Lock idle capital for flexible durations (7, 30, 90, 180, or 365 days). Earn daily compounding yields with 100% principal guarantee returned upon lock maturity.',
      steps: [
        {
          num: '1',
          title: 'Choose Duration & Term',
          desc: 'Select from short-term (7–30 days) or long-term (90–365 days) locked savings tiers based on your preferred liquidity timeline.'
        },
        {
          num: '2',
          title: 'Lock Your Assets',
          desc: 'Commit your USDT or fiat funds from your account balance with zero front-end fee.'
        },
        {
          num: '3',
          title: 'Receive Fixed Compounding Yield',
          desc: 'Earn fixed daily interest credited directly to your portfolio. Principal unlocks immediately at the end of the term.'
        }
      ],
      highlights: [
        '100% Principal protection guaranteed',
        'Flexible lock-in terms from 7 to 365 days',
        'Higher yield than standard savings accounts',
        'Daily interest tracking and notifications'
      ],
      cta: 'Start Staking',
      link: '/app/staking',
      color: 'indigo'
    },
    p2p: {
      title: 'P2P Escrow Exchange',
      tagline: 'Direct Peer-to-Peer Trading with Escrow Protection',
      badge: '0% Platform Fee',
      desc: 'Buy and sell USDT and local currencies directly with other verified users around the globe. Every transaction is backed by our automated cryptographic escrow system.',
      steps: [
        {
          num: '1',
          title: 'Create or Select an Offer',
          desc: 'Browse live buy/sell listings with custom prices and payment methods, or publish your own custom trading advertisement.'
        },
        {
          num: '2',
          title: 'Funds Secured in Escrow',
          desc: 'When an order is initiated, the seller’s crypto is locked securely in RPM Escrow to prevent fraud or chargebacks.'
        },
        {
          num: '3',
          title: 'Payment & Instant Release',
          desc: 'The buyer completes payment via their selected method. Once the seller confirms receipt, the escrow instantly releases the crypto.'
        }
      ],
      highlights: [
        'Zero fee for peer-to-peer exchanges',
        'Multi-currency and local bank support',
        'Institutional dispute resolution team',
        'Real-time encrypted trade chat'
      ],
      cta: 'Trade P2P Now',
      link: '/app/p2p',
      color: 'teal'
    },
    invest: {
      title: 'Investment ROI Plans',
      tagline: 'Automated Daily Returns with Capital Preservation',
      badge: '3.0% – 8.0% Daily Returns',
      desc: 'Participate in curated multi-market algorithmic trading and venture portfolios offering daily ROI payouts directly to your wallet.',
      steps: [
        {
          num: '1',
          title: 'Select Investment Plan',
          desc: 'Pick a plan (Starter, Standard, Growth, or Premium) that matches your capital level and risk tolerance.'
        },
        {
          num: '2',
          title: 'Activate Portfolio',
          desc: 'Allocate funds from your wallet or deposit directly via bank wire or cryptocurrency.'
        },
        {
          num: '3',
          title: 'Collect Daily ROI',
          desc: 'Returns accrue automatically every 24 hours and can be withdrawn or reinvested immediately.'
        }
      ],
      highlights: [
        'Daily automated payout distribution',
        'Transparent fee-free structure',
        'Compound auto-reinvestment option',
        'Full portfolio transparency'
      ],
      cta: 'View Investment Plans',
      link: '/app/invest',
      color: 'emerald'
    }
  };

  const current = products[activeTab];

  return (
    <div className="min-h-screen bg-gray-50/50 py-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Page Header */}
        <div className="text-center max-w-3xl mx-auto mb-12">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-brand/10 text-brand text-xs font-bold uppercase tracking-wider mb-4">
            <Sparkles size={13} /> Complete Platform Guide
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-gray-900 tracking-tight">
            How RPM Works
          </h1>
          <p className="text-gray-600 mt-4 text-base sm:text-lg leading-relaxed">
            Discover how our ecosystem makes Real Estate Properties, Locked Savings, P2P Trading, and Investment Plans effortless and secure.
          </p>
        </div>

        {/* 4 Multi-Product Tabs */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 max-w-4xl mx-auto mb-10">
          <button
            onClick={() => setActiveTab('properties')}
            className={`flex items-center justify-center gap-2 py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm transition-all shadow-sm border ${
              activeTab === 'properties'
                ? 'bg-amber-500 text-white border-amber-500 shadow-amber-500/20 shadow-md'
                : 'bg-white text-gray-700 border-gray-200 hover:border-amber-300 hover:bg-amber-50/50'
            }`}
          >
            <Home size={16} /> Real Estate Properties
          </button>
          <button
            onClick={() => setActiveTab('staking')}
            className={`flex items-center justify-center gap-2 py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm transition-all shadow-sm border ${
              activeTab === 'staking'
                ? 'bg-indigo-600 text-white border-indigo-600 shadow-indigo-600/20 shadow-md'
                : 'bg-white text-gray-700 border-gray-200 hover:border-indigo-300 hover:bg-indigo-50/50'
            }`}
          >
            <Layers size={16} /> Locked Savings
          </button>
          <button
            onClick={() => setActiveTab('p2p')}
            className={`flex items-center justify-center gap-2 py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm transition-all shadow-sm border ${
              activeTab === 'p2p'
                ? 'bg-teal-600 text-white border-teal-600 shadow-teal-600/20 shadow-md'
                : 'bg-white text-gray-700 border-gray-200 hover:border-teal-300 hover:bg-teal-50/50'
            }`}
          >
            <ArrowLeftRight size={16} /> P2P Exchange
          </button>
          <button
            onClick={() => setActiveTab('invest')}
            className={`flex items-center justify-center gap-2 py-3.5 px-4 rounded-2xl font-bold text-xs sm:text-sm transition-all shadow-sm border ${
              activeTab === 'invest'
                ? 'bg-brand text-white border-brand shadow-brand/20 shadow-md'
                : 'bg-white text-gray-700 border-gray-200 hover:border-brand hover:bg-emerald-50/50'
            }`}
          >
            <TrendingUp size={16} /> Invest Plans
          </button>
        </div>

        {/* Selected Product Deep-Dive Card */}
        <div className="bg-white rounded-3xl border border-gray-100 shadow-xl p-6 sm:p-10 mb-12">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-8 border-b border-gray-100">
            <div>
              <span className="text-xs font-bold px-3 py-1 rounded-full bg-brand/10 text-brand inline-block mb-2">
                {current.badge}
              </span>
              <h2 className="text-2xl sm:text-3xl font-bold text-gray-900">{current.title}</h2>
              <p className="text-sm font-semibold text-gray-500 mt-1">{current.tagline}</p>
            </div>
            <Link
              to={current.link}
              className="inline-flex items-center justify-center gap-2 bg-brand hover:bg-brand-dark text-white font-bold text-sm px-6 py-3 rounded-xl shadow-md hover:shadow-lg transition"
            >
              {current.cta} <ArrowRight size={16} />
            </Link>
          </div>

          <p className="text-gray-600 text-base leading-relaxed my-6">
            {current.desc}
          </p>

          {/* 3 Step Workflow */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-8">
            {current.steps.map((s) => (
              <div key={s.num} className="bg-gray-50/80 rounded-2xl p-6 border border-gray-100 flex flex-col justify-between">
                <div>
                  <div className="w-10 h-10 rounded-xl bg-brand text-white font-extrabold flex items-center justify-center text-base mb-4 shadow-sm">
                    {s.num}
                  </div>
                  <h3 className="font-bold text-gray-900 text-lg mb-2">{s.title}</h3>
                  <p className="text-sm text-gray-600 leading-relaxed">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Key Advantages */}
          <div className="bg-emerald-50/60 border border-emerald-100/80 rounded-2xl p-6">
            <h4 className="font-bold text-brand text-sm uppercase tracking-wider mb-4 flex items-center gap-2">
              <ShieldCheck size={18} /> Key Guarantees & Features
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {current.highlights.map((h, i) => (
                <div key={i} className="flex items-center gap-2.5 text-sm text-gray-800">
                  <CheckCircle2 size={16} className="text-brand shrink-0" />
                  <span>{h}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* General Universal Onboarding Process */}
        <div className="text-center max-w-2xl mx-auto mb-8">
          <h2 className="text-2xl font-bold text-gray-900">Universal 3-Step Setup</h2>
          <p className="text-sm text-gray-500 mt-1">Get started in under 3 minutes with zero paperwork</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 text-center">
            <div className="w-12 h-12 bg-brand/10 text-brand rounded-2xl flex items-center justify-center font-bold text-lg mx-auto mb-4">
              1
            </div>
            <h3 className="font-bold text-gray-900 text-base mb-1">Create Free Account</h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Register with your email and password. No immediate identity verification required to browse.
            </p>
          </div>
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 text-center">
            <div className="w-12 h-12 bg-brand/10 text-brand rounded-2xl flex items-center justify-center font-bold text-lg mx-auto mb-4">
              2
            </div>
            <h3 className="font-bold text-gray-900 text-base mb-1">Deposit or Fund Wallet</h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Deposit via Bank wire, ACH, or USDT (TRC20 / ERC20) with zero processing fees.
            </p>
          </div>
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 text-center">
            <div className="w-12 h-12 bg-brand/10 text-brand rounded-2xl flex items-center justify-center font-bold text-lg mx-auto mb-4">
              3
            </div>
            <h3 className="font-bold text-gray-900 text-base mb-1">Deploy Across 4 Products</h3>
            <p className="text-xs text-gray-500 leading-relaxed">
              Diversify between real estate properties, high-yield staking, P2P trades, or daily ROI plans.
            </p>
          </div>
        </div>

        <div className="text-center mt-12">
          <Link
            to="/signup"
            className="inline-flex items-center gap-2 bg-brand hover:bg-brand-dark text-white px-8 py-4 rounded-2xl font-bold text-base shadow-lg hover:shadow-xl transition"
          >
            Create Your Free Account <ArrowRight size={18} />
          </Link>
        </div>
      </div>
    </div>
  );
}