// AUTO-GENERATED — human-sounding investor-chat corpus.
// Produced by the 'humanize-chat-corpus' multi-agent workflow (parallel authors
// + an adversarial "does this sound like AI?" filter pass). Do not hand-edit in
// bulk; regenerate from the workflow if you want to refresh the voice.
// 1153 standalone lines, 52 topic-weaving templates.

export const HUMAN_MSGS: string[] = [
  "just topped up another 500",
  "payout hit again this morning 🙌",
  "waiting on my withdrawal, anyone else slow rn?",
  "put in 250 to start, seeing how it goes",
  "yo did anyone else get their daily yet",
  "mine came through at like 6am",
  "still nothing on my end lol",
  "added 1k last night, fingers crossed",
  "how long do withdrawals usually take",
  "got my 40 bucks today not bad",
  "topped up to 2k total now",
  "anyone waiting on a payout since yesterday",
  "small deposit for now, 100",
  "wallet just updated nice",
  "daily came in right on time today",
  "im confused where does the payout show up",
  "just sent 300 in, first time here",
  "withdrawal pending for 2 days is that normal",
  "lol my payout was like 3 dollars today",
  "reinvested my returns instead of pulling out",
  "deposit finally cleared took a while",
  "another day another payout 📈",
  "how much did everyone start with",
  "put 500 in monday, already seeing a lil something",
  "still learning how this works ngl",
  "mine says processing been a few hrs",
  "cashed out 200 yesterday hit my account today",
  "topping up when i get paid friday",
  "dailys been consistent for me so far tbh",
  "is there a minimum withdrawal amount",
  "just added another 750",
  "got nothing this morning anyone else",
  "returns lookin decent tbh",
  "deposited 1500 lets see",
  "my withdrawal went through in like an hour",
  "waiting on 400 to hit",
  "started with 50 just testing the waters",
  "payout came thru while i was asleep",
  "anyone know the withdrawal fee",
  "bumped my deposit up to 3k",
  "daily hit but smaller than yesterday idk why",
  "first payout ever just landed 🔥",
  "still pending after 24hrs getting nervous",
  "put in 600 this week",
  "wallet balance finally moving",
  "how often do the payouts drop",
  "topped off my wallet again",
  "mine took 3 days to withdraw fyi",
  "just threw in 200 more",
  "returns been steady nothing crazy",
  "anybody else deposit today",
  "got my daily, 25 bucks",
  "waiting on my cashout still nothing",
  "added 1k, now we wait",
  "payout schedule kinda random for me",
  "deposited last night still not showing",
  "cashed out half kept the rest in",
  "small one today but ill take it",
  "topped up 350 no issues",
  "does the daily come at the same time everyday",
  "just pulled out 500 clean",
  "my first deposit went smooth",
  "still waiting bruh its been all day",
  "put another 900 in",
  "kinda feel like the more u put in the more comes back idk",
  "anyone had trouble withdrawing lately",
  "daily came in twice? or am i tripping",
  "deposited 100 to start small",
  "waiting on payout been 2 hrs chill",
  "just added 2k big move for me",
  "mine cleared instantly this time",
  "how do i even withdraw someone help",
  "payout landed 💰",
  "topped up before the weekend",
  "still no daily anyone else missing theirs",
  "put in 400 lets go",
  "withdrawal took forever but it came",
  "just deposited my first 250",
  "returns slower this week or is it just me",
  "cashed out 1k no problems",
  "adding 500 tonight when i get home",
  "daily hitting most days ngl",
  "my wallet says 0 did i mess up",
  "topped up another grand",
  "waiting on 150 withdrawal",
  "got 60 today decent",
  "just put in 800",
  "payout pending anyone know how long",
  "reinvested everything again",
  "small deposit 75 for now",
  "mine finally showed up after 2 days",
  "adding more once this clears",
  "daily hit, 30 bucks nice",
  "withdrawal request in, waiting",
  "just topped up 1200",
  "returns lookin good this morning",
  "anyone else deposit not showing yet",
  "cashed out 300 just to test it works",
  "put 500 back in after withdrawing",
  "my payout was tiny today lol",
  "deposited and immediately got nervous ngl",
  "waiting on my money still",
  "added another 250 this week",
  "daily came through 👀",
  "how long till my deposit shows",
  "just withdrew 700 smooth",
  "topping up slowly, 100 at a time",
  "payout hit right when i woke up",
  "still pending idk whats going on",
  "put in 3k lets see what happens",
  "returns been ok not gonna lie",
  "cashed out my first payout today",
  "anyone waiting on withdrawals rn",
  "deposited 200 all good",
  "daily didnt come today weird",
  "just added 600 more",
  "my withdrawal cleared in 30 min",
  "topped up to 5k total finally",
  "small payout but it keeps coming",
  "waiting on 250 to hit my wallet",
  "put another 400 in tonight",
  "returns hit, reinvesting",
  "deposit stuck on pending help",
  "cashed out 500 no fees somehow",
  "just topped up 150",
  "daily been solid all week",
  "anyone else withdrawal slow today",
  "added 1k this morning",
  "my payout landed 🙌",
  "still waiting on my deposit to clear",
  "put in 350 first timer here",
  "returns kinda low today but whatever",
  "withdrew 200 came fast",
  "topped up again cant stop lol",
  "daily hit 45 bucks",
  "waiting on payout for hours now",
  "just deposited 900",
  "mine cleared same day nice",
  "adding 500 when i get paid",
  "payout came in small but steady",
  "still no withdrawal 3 days now",
  "topped off 250 more",
  "returns been decent this month",
  "just pulled 400 out",
  "deposit finally showing up",
  "daily payout on time again",
  "put in 100 to try it out",
  "cashed out and reinvested half",
  "waiting on my 600 still nothing 😭",
  "topped up 2k feeling good",
  "my payout hit while at work",
  "anyone know why my deposit is delayed",
  "just added another 300",
  "locked in the 90 day pool finally",
  "that duplex listing filled up fast lol",
  "compounding slowly doing its thing i think",
  "anyone else staking the whole bag rn",
  "just locked another 30 days",
  "yields dipped a lil this week huh",
  "how long till my stake unlocks again",
  "bought into the atlanta rental last night 🙌",
  "wait is the 60 day pool still open",
  "reinvested my payout instead of pulling it",
  "duplex one sold out before i even refreshed",
  "staking apy looks nice ngl",
  "compounding weekly and just letting it ride",
  "someone explain locking to me pls",
  "grabbed 2 units in that phoenix listing",
  "yields been steady for me tbh",
  "im locked till march lol send help",
  "that beachfront property went quick",
  "apy vs apr im always confused which one shows",
  "just compounding and touching nothing",
  "new listing dropped anybody in",
  "rental returns hit my account this morning 💰",
  "locked position feeling good so far",
  "why is my stake still pending",
  "the miami condo filled in like an hour",
  "staking rewards small but consistent",
  "did the yield change or is it just me",
  "put half in staking half in property",
  "locked 180 days im insane apparently",
  "anyone waiting on their rental payout too",
  "compounding is underrated fr",
  "how do i unlock early do i lose rewards",
  "snagged the last unit in the dallas one 🔥",
  "yields lookin healthy this month",
  "just restaked everything again",
  "that studio listing sold out damn",
  "im scared to lock long tbh",
  "payout landed right on time nice",
  "staking the minimum just to test it",
  "the property pools fill so fast now",
  "locked in and forgetting about it",
  "wait my compounding didnt trigger?",
  "grabbed into the townhouse listing",
  "yields down but whatever im long",
  "anyone doing the 90 day over 30",
  "new rental prop looks solid ngl",
  "locked it and moved on ngl",
  "how often does compounding actually run",
  "the vegas listing went in minutes lol",
  "restaked my rewards like a good boy",
  "staking apy still beats my bank lmao",
  "which pool are yall in",
  "bought into two properties this week 👀",
  "my lock ends tomorrow finally",
  "compounding hit and i barely noticed",
  "is the rental income monthly or weekly",
  "locked more than i shouldve honestly",
  "that listing had a waitlist already?",
  "yields consistent, cant complain",
  "just staked, wish me luck",
  "anyone else obsessed with checking their apy",
  "the duplex returns look decent",
  "unlocked and immediately relocked lol",
  "property tab loads slow for anyone else",
  "staking rewards feel like free money kinda",
  "in the 60 day, no regrets yet",
  "how do rental returns get calculated",
  "grabbed a piece of the chicago listing",
  "compounding quietly stacking up",
  "my stake unlocks in 12 days counting down",
  "listings sell out too fast man",
  "reinvested again cant stop wont stop",
  "yields dipped but still positive",
  "locked in for the long haul i guess",
  "anyone in the new staking pool",
  "that seattle property filled instantly",
  "just letting compounding cook",
  "apy went up did anyone catch that",
  "waiting on my first rental payout 😅",
  "staked and stepped away",
  "the listing sold before i finished reading it",
  "compounding is the real move imo",
  "how long are yall locking for",
  "put a chunk in the 90 day",
  "rental returns hit smaller than expected",
  "restaking > withdrawing for me",
  "locked and honestly forgot about it",
  "yields holding steady, im happy",
  "new property drop when",
  "grabbed into the austin rental 💰",
  "my compounding schedule confuses me",
  "is staking safer than the property side",
  "locked till summer, praying lol",
  "that listing was gone in 3 min",
  "just compounded, feels good",
  "anyone else staking their referral bonus",
  "unlock day is my favorite day",
  "the returns on that duplex tho",
  "staked more after seeing the apy",
  "yields kinda flat this week",
  "locked position, no touching allowed",
  "which property yall buying into next",
  "compounding away while im not looking",
  "rental payout came through finally",
  "staking min just to feel included lol",
  "listings need bigger supply fr",
  "locked in deep, cant back out now",
  "how do i see my next compound date",
  "grabbed the last two units 🔥",
  "yields nice but lock is long",
  "just restaked, on autopilot now",
  "anyone confused by the unlock fees",
  "the property returns are actually paying",
  "staked and forgot my own timeline",
  "new listing filled while i was at work",
  "compounding adds up slower than i thought",
  "locked 30, might do 90 next",
  "rental income landed, small but real",
  "why did my apy drop overnight",
  "bought into a property first time nervous",
  "staking rewards trickling in nice",
  "that listing sold out so fast lmao",
  "locked till march, see yall then",
  "compounding is boring in a good way",
  "anyone pulling profits or all reinvest",
  "my stake finally unlocked woo",
  "the returns arent bad for passive tbh",
  "grabbed into two listings back to back",
  "yields steady enough for me",
  "locked long term, talk to me in a year",
  "rental payout smaller than i hoped 😭",
  "just staked the rest of my balance",
  "how does early unlock work exactly",
  "property pool filled before lunch",
  "compounding hit, adding up slowly",
  "staked and now i just wait",
  "which lock period is best honestly",
  "that condo listing was gone instantly",
  "reinvesting every payout no cap",
  "yields up a bit this week nice",
  "locked in, fingers crossed",
  "anyone else staking daily lol",
  "the duplex filled in like 5 min",
  "compounding quietly, no complaints here",
  "just relocked for another round",
  "rental returns finally showing up",
  "staked and ignoring it for months lol",
  "sol network flying today",
  "gas ate half my transfer 😭",
  "took 3 confirmations but it landed",
  "usdt still pending ffs",
  "anyone else seeing eth gas insane rn",
  "just sent via sol, cheapest by far",
  "waiting on 2nd confirm come on",
  "btc fees killed me this morning",
  "moved my usdt over, painless honestly",
  "why is the network so slow tonight",
  "gas was like 40 bucks lmao no thanks",
  "sol under a cent to send",
  "my tx been pending 20 min already",
  "finally confirmed 🙌",
  "trc20 or erc20 for the deposit?",
  "erc20 gas is robbery atm",
  "use trc20 way cheaper",
  "sent 500 usdt, showed up in 2 min",
  "network congested rn hold off",
  "which wallet u guys using",
  "metamask acting up again for anyone?",
  "sol landed instant nice",
  "still 0 confirmations after 15 min bruh",
  "double check the address before sending pls",
  "sent to the wrong network once, never again",
  "phantom been solid for me",
  "gas fees been rough all week ngl",
  "how many confirms till it shows",
  "6 confirms needed apparently ugh",
  "just funded with btc, took forever tho",
  "usdt on tron is the way rn",
  "eth mempool looks clogged",
  "anyone know when sol network stabilizes",
  "my transfer stuck on unconfirmed",
  "sent sol, done before i put my phone down",
  "gas ate like 30% of a small transfer damn",
  "deposit confirmed finally lets go",
  "test with a small amount first",
  "wallet address updated? mine looks different",
  "why do fees spike at the worst times",
  "trust wallet or metamask thoughts",
  "sol fees are basically free lol",
  "3 confirmations and counting",
  "usdt went through smooth this time",
  "network fee higher than my actual send lmao",
  "check ur gas before you hit send",
  "btc taking an hour to confirm today",
  "moved to sol just for the speed",
  "anyone having issues funding via usdt",
  "pending pending pending come onnn",
  "gas dropped a bit, good time to send",
  "confirmed in one block, sol is nuts",
  "erc20 fees make me wanna cry",
  "how long does btc usually take",
  "just double checked the deposit address twice",
  "sol network down for anyone else?",
  "sent it, waiting on network now",
  "usdt landed instant on tron 🔥",
  "fees eating me alive today",
  "which network has lowest gas rn",
  "transfer stuck, is the chain congested",
  "copy paste the address never type it",
  "6 confirmations done, all good",
  "gas so high i just waited a day",
  "usdt showing up slow anyone else",
  "wallet not connecting ugh",
  "sent btc 40 min ago still nothing",
  "sol fees vs eth is night and day",
  "deposit pending, staff how long usually",
  "confirmed 🙌 that was quick",
  "network fees calmed down finally",
  "my usdt vanished into pending limbo lol",
  "how many blocks for a confirm here",
  "eth gas at 80 gwei nope",
  "funded via btc, patience required lol",
  "anyone else network lagging",
  "sent to trc20 by mistake help",
  "gas fees are a scam sometimes fr",
  "usdt deposit smooth no complaints",
  "still waiting on that first confirmation",
  "check the memo tag before u send",
  "btc mempool backed up today",
  "moved everything to sol tbh",
  "confirmations slow rn everyone chill",
  "my wallet balance not updating",
  "sent usdt, took 5 min all good",
  "gas price ridiculous this hour",
  "which is faster sol or eth",
  "1 confirm down 5 to go",
  "usdt on eth cost me a fortune in gas",
  "deposit still not showing, worried",
  "sent, now we wait on confirms",
  "phantom froze mid transaction yikes",
  "low gas window rn, send now",
  "btc confirmed after 3 blocks finally",
  "why is sol so cheap and eth so not",
  "usdt pending for an hour is that normal",
  "gas ate my lunch money 😭",
  "sol deposit hit instantly",
  "anyone else stuck on unconfirmed",
  "always verify the network matches",
  "sent 1k usdt, landed in minutes",
  "eth fees keeping me on tron ngl",
  "confirmations rolling in nice",
  "wallet says pending but nothing moving",
  "gas fees lower on weekends i swear",
  "funded with sol, easy enough",
  "btc slow again classic",
  "usdt confirmed lets gooo",
  "how do i check confirmation count",
  "network congestion is real tonight",
  "sent to the deposit address, fingers crossed",
  "sol so fast i thought it failed lol",
  "gas quote changed before i even sent",
  "usdt landed, all good on my end",
  "3rd confirm just came through",
  "eth gas down a bit finally",
  "moved funds via sol zero stress",
  "still 0 confirms this is painful",
  "which chain u recommend for deposits",
  "btc took 5 confirms but its here now",
  "gas fees back up again ffs",
  "deposit confirmed after a long wait phew",
  "just sent usdt trc20, way cheaper than erc20",
  "dashboard finally loading fast today",
  "support actually replied in like 5 min omg",
  "anyone else app freezing on the payout tab",
  "referral link doing numbers ngl",
  "payout hit in under an hour, not bad",
  "my ticket been open 3 days now 😭",
  "app feels smoother after the update tbh",
  "why is the app so slow tonight lol",
  "got my referral bonus finally",
  "dashboard wont refresh for me, anyone else",
  "clean new layout ngl",
  "support straight up ghosted me",
  "withdrawal still pending since morning",
  "app crashes every time i open charts",
  "5 referrals this week 🔥",
  "is the site down or just me",
  "dark mode they added is nice",
  "payouts been quick lately",
  "cant find the referral tab anymore, where did it go",
  "ticket #4471 anyone from support pls",
  "numbers actually updating live now",
  "app keeps logging me out ugh",
  "referral dashboard looks way better now",
  "who else waiting on a payout rn",
  "support was actually helpful today, shocking",
  "the loading spinner just spins forever",
  "bonus credited instantly, nice",
  "new feature is kinda confusing not gonna lie",
  "anyone know how long payouts usually take",
  "dashboard down again great",
  "referral bonus was bigger this month idk why",
  "app running smooth after the update 🙌",
  "my balance showing wrong on the dashboard",
  "ticket sorted in a day, respect",
  "why cant i withdraw yet",
  "that new stats page is clean",
  "payout came through overnight",
  "app so laggy on my old phone lol",
  "referral link finally working again",
  "been on hold with support forever",
  "dashboard numbers look off today, anyone else",
  "new notifications thing is actually useful",
  "withdrawal went through fast today 💰",
  "app froze mid transaction bruh",
  "got 3 people to sign up with my link",
  "support email bouncing back for anyone else",
  "update dropped, feels faster",
  "payout tab not loading again",
  "referral earnings adding up ngl",
  "cant log in on the app rn, help",
  "dashboard finally shows my full history",
  "support replied but didnt fix anything",
  "withdrawal hit my wallet quick",
  "app keeps crashing after the update smh",
  "new referral tiers look interesting",
  "anyone else stuck on the loading screen",
  "payout was late but it came",
  "the ui got a facelift, i like it",
  "ticket still open, going on a week now",
  "referral bonus actually showed this time",
  "app super slow during peak hours",
  "dashboard glitching hard tonight",
  "support actually called me back, wild",
  "got my payout no issues today",
  "why is the app eating my battery lol",
  "referral link stopped tracking for me",
  "new dashboard widgets are nice",
  "withdrawal pending 2 days now, anyone else",
  "support been slow this week fr",
  "app finally stopped crashing thank god",
  "referral numbers looking decent",
  "dashboard loads instant now, love it",
  "cant submit a ticket, the form broke",
  "payout came in early this morning",
  "new feature nobody asked for but ok",
  "app froze again, gonna reinstall",
  "referral bonus never showed up, help",
  "support was quick this time, nice change",
  "dashboard timezone is all wrong for me",
  "withdrawal smooth as usual",
  "the update fixed my login issue finally",
  "anyone getting error 500 on payouts",
  "referral tab loading slow af",
  "got my bonus after messaging support",
  "dashboard down for maintenance again",
  "app runs way better on wifi lol",
  "payout took 6 hours today, kinda slow",
  "new analytics tab is actually good",
  "support ticket auto closed with no reply ugh",
  "referral link doing better than i thought",
  "cant see my transaction history anymore",
  "app keeps asking me to update every day",
  "withdrawal finally cleared 🙌",
  "dashboard froze when i tapped payout",
  "support agent was super patient tbh",
  "referral bonus credited right away nice",
  "the app is buttery smooth now",
  "payout stuck in processing forever",
  "new dark theme easy on the eyes",
  "anyone else app not opening at all",
  "support been faster lately ngl",
  "referral earnings hit my account today",
  "dashboard showing double entries, weird",
  "support took forever but sorted it",
  "withdrawal fee wasnt clear, anyone know",
  "app lag is unreal today",
  "new feature makes tracking way easier",
  "payout notifications actually work now",
  "referral link gave me a 404 lol",
  "dashboard finally accurate after the fix",
  "cant reach support at all today",
  "got paid out in minutes 🔥",
  "app crashed and lost my progress smh",
  "referral program actually worth it now",
  "new update slowed my phone down ngl",
  "support chat kept disconnecting on me",
  "withdrawal processed no drama",
  "dashboard wont let me export anything",
  "payout delay again whats going on",
  "referral tracker is finally accurate",
  "app froze on the login screen bruh",
  "support followed up on their own, didnt expect that",
  "new layout took me a sec to get used to",
  "withdrawal hit instantly this time",
  "dashboard keeps buffering nonstop",
  "got my referral bonus doubled somehow lol",
  "app finally has search thank god",
  "payout landed while i was sleeping",
  "support ticket number never got assigned",
  "referral link back up and running",
  "dashboard runs smooth on desktop at least",
  "monday already? nah",
  "this coffee saving my life rn",
  "who watched the game last night",
  "so tired today man",
  "raining again over here ugh",
  "anyone else cant sleep",
  "just woke up dont talk to me lol",
  "gym or nap. nap winning",
  "traffic is insane this morning",
  "coffee number 3 and its only 9am",
  "why is it so cold today",
  "weekend cant come fast enough",
  "my back hurts from sitting all day",
  "lunch time whats everyone eating",
  "pizza again for me lol",
  "its already dark out here",
  "who else stuck at work",
  "kids finally asleep, peace at last",
  "my dog woke me up at 5am bruh",
  "need a vacation asap",
  "anyone watching the world cup",
  "raining sideways rn 😅",
  "coffee tastes weird today idk",
  "up early for no reason again",
  "tuesday feels like a friday somehow",
  "so hungry i could eat anything",
  "new coffee shop opened near me, decent",
  "cant feel my legs after leg day",
  "wife made tacos tonight yesss",
  "why am i still awake",
  "ac broke in this heat, help",
  "its snowing where im at",
  "long day already and its barely noon",
  "grabbing donuts brb",
  "sunset today was unreal",
  "who else works nights",
  "phone battery dying send help",
  "meeting after meeting today ugh",
  "finally friday lets goooo",
  "raining all week here",
  "coffee then more coffee",
  "this sandwich actually slaps ngl",
  "sitting in traffic for an hour now",
  "wish i could sleep in tomorrow",
  "so much laundry to do",
  "its 40 and windy nope",
  "second cup already",
  "anyone else hate mondays",
  "cooking dinner smells amazing",
  "cant stop yawning today",
  "went for a run this morning, feel good",
  "my team lost last night 😭",
  "power went out for a bit here",
  "cereal for dinner dont judge",
  "who stayed up for the fight",
  "hot out today fr",
  "tea over coffee any day imo",
  "back to work after holiday is brutal",
  "napped too long now im groggy",
  "supposed to storm later tonight",
  "brunch this weekend? im in",
  "cant find my keys again lol",
  "so foggy this morning couldnt see",
  "thai food tonight, worth it",
  "alarm didnt go off, panic mode",
  "beach day this weekend hopefully",
  "coffee machine broke worst day ever",
  "gym was packed today ugh",
  "leftovers again",
  "raining but i forgot my umbrella",
  "sunday scaries hitting hard",
  "anyone else weirdly love rainy days",
  "too hot to do anything today",
  "made pasta from scratch kinda proud",
  "traffic cleared up finally",
  "so sleepy after lunch",
  "weather app lied again",
  "grabbing coffee whos coming",
  "watched a movie till 2am, regret",
  "knees hurt when it rains lol",
  "bbq this weekend cant wait",
  "office fridge stinks again",
  "cold brew season for me",
  "walked the dog in the rain, fun",
  "nobody told me it was gonna snow",
  "third coffee dont talk to me",
  "long commute today ugh",
  "breakfast for dinner tonight",
  "so windy my hat flew off",
  "who watched the race sunday",
  "gonna sleep early tonight for once",
  "why is monday like this",
  "sunny finally after a week of rain",
  "meal prepping on a sunday like an adult",
  "tired but cant fall asleep",
  "burnt my toast, great start",
  "anyone else drink way too much coffee",
  "heatwave over here send ice",
  "playoffs tonight lets go",
  "spilled coffee on my shirt already",
  "raining so hard i can barely see",
  "long week and its only wednesday",
  "made curry, whole house smells great",
  "my feet are killing me today",
  "who else hates waking up early",
  "sunset was gorgeous tonight",
  "stuck in traffic again send snacks",
  "coffee first then we talk",
  "so cold i can see my breath",
  "tacos for lunch no regrets",
  "might nap the whole weekend honestly",
  "my back is done after that hike",
  "who watched the game omg what an ending",
  "raining cats and dogs out here",
  "need a coffee iv at this point",
  "so much to do today im tired already",
  "made pancakes this morning yum",
  "highway traffic is a nightmare",
  "sleeping in tomorrow finally",
  "way too hot to cook",
  "gym then breakfast lets go",
  "why does monday come so fast",
  "storm knocked out my wifi ugh",
  "pizza in bed rn peak comfort",
  "long shift today im beat",
  "raining again seriously",
  "watched the match at the pub, good vibes",
  "so tired i cant even think",
  "cooked way too much food tonight",
  "walking to work in this cold nope",
  "who else skips breakfast",
  "snow day maybe? fingers crossed",
  "grabbing lunch anyone hungry",
  "me and my alarm are not friends",
  "sunny out finally, getting outside",
  "coffee number 4 send help lol",
  "raining all weekend, plans ruined",
  "so sleepy at my desk rn",
  "made soup, cold out so perfect",
  "traffic made me late again ugh",
  "gym was empty today loved it",
  "weather cant make up its mind",
  "who watched the finals last night",
  "breakfast for dinner again",
  "long day tomorrow better sleep",
  "its freezing i want summer back",
  "coffee then a nap sounds perfect",
  "raining but im staying cozy inside",
  "so hungry whens lunch",
  "lets go 🔥",
  "no way",
  "fr?",
  "same here",
  "lol facts",
  "big if true",
  "nice one",
  "yooo",
  "wait what",
  "gm all",
  "morning everyone",
  "im in",
  "count me in",
  "here we go",
  "aight bet",
  "solid",
  "not bad",
  "hmm interesting",
  "wild",
  "sheesh",
  "damn",
  "bruh",
  "lmaooo",
  "stop it",
  "no cap",
  "for real tho",
  "thats crazy",
  "ok wow",
  "lets gooo",
  "finally",
  "about time",
  "yesss",
  "clean",
  "huh",
  "wait fr",
  "say less",
  "im dead 😭",
  "crying rn",
  "based",
  "goated",
  "kinda nervous ngl",
  "lowkey worried",
  "we good?",
  "anyone else",
  "hello?",
  "yo whats good",
  "sup all",
  "gm gm",
  "afternoon folks",
  "evening everyone",
  "still waiting",
  "any updates?",
  "wheres my payout",
  "took long enough",
  "not seeing it yet",
  "loading forever",
  "app being weird",
  "site down for anyone",
  "cant log in help",
  "reset my pw ugh",
  "works now nvm",
  "my bad",
  "fixed it",
  "ohhh i see",
  "makes sense",
  "gotcha",
  "ah okay",
  "thanks fam",
  "appreciate it",
  "ty ty",
  "much love",
  "respect 🙌",
  "hey newbies",
  "first time here",
  "just joined",
  "new here",
  "whats this about",
  "someone explain lol",
  "im confused",
  "wait im lost",
  "back again",
  "long time no see",
  "missed yall",
  "quiet in here today",
  "dead chat",
  "wake up people",
  "anyone awake",
  "3am scrolling",
  "cant sleep lol",
  "same tbh",
  "mood",
  "felt that",
  "real",
  "100%",
  "exactly",
  "preach",
  "you get it",
  "nah fr",
  "yeah no",
  "idk man",
  "we'll see",
  "fingers crossed",
  "praying 🙏",
  "hopefully",
  "lets hope",
  "still waiting on mine",
  "just lurking",
  "hi from brazil",
  "india here",
  "manila here 🙌",
  "lagos represent",
  "uk gang",
  "texas checking in",
  "hola everyone",
  "salaam all",
  "namaste",
  "bonjour",
  "cheers mate",
  "coffee first brb",
  "back",
  "ok im here now",
  "brb",
  "gtg later",
  "peace out",
  "night all",
  "sleep well folks",
  "later gang",
  "catch yall tmrw",
  "one sec",
  "hold up",
  "wait for me",
  "im slow today lol",
  "ugh mondays",
  "friday finally",
  "weekend vibes",
  "any news yet",
  "welcome fam",
  "im keeping it small till i see a few payouts",
  "anyone actually withdrawn a big amount yet?",
  "sounds too good but here i am lol",
  "why is my balance not updating",
  "how long does a withdrawal usually take",
  "ngl im a little nervous putting more in",
  "is this legit or am i about to learn a lesson",
  "dashboard says pending since yesterday",
  "ok but whats the actual catch here",
  "started with 50 just to test",
  "anyone else waiting on a payout rn",
  "returns look kinda high for staking ngl",
  "how do i know this isnt just numbers on a screen",
  "waiting to withdraw before i believe any of it",
  "genuine q where does the yield actually come from",
  "im in but only with money i can lose",
  "does anyone have a screenshot of a real cashout",
  "why does the app keep logging me out",
  "skeptical but the chat seems active at least",
  "what happens if the platform just disappears one day",
  "put in a bit last week, still watching",
  "not touching my main savings for this",
  "anyone verified the team behind rpm?",
  "my referral bonus never showed up btw",
  "how safe is the real estate side really",
  "lowkey worried this is one of those things",
  "curious how they can even afford these rates",
  "still on the fence honestly",
  "tried withdrawing $20 first, waiting",
  "does the balance update instantly or delayed",
  "why is there a fee i didnt see mentioned",
  "small stake for now, no fomo here",
  "anyone been in longer than 6 months",
  "numbers go up but can i actually take it out",
  "just here reading before i commit anything",
  "whats the minimum to withdraw",
  "feels a bit too smooth ngl",
  "anyone got their money out clean no issues",
  "my transaction is stuck on processing, help",
  "not saying its a scam but not saying it isnt",
  "how do payouts work, daily or what",
  "im treating this as high risk not savings",
  "why do i need to refer ppl to unlock stuff",
  "wallet connected but nothing showing up",
  "keeping expectations low tbh",
  "do they charge anything on deposits",
  "anyone regret going in big",
  "i wanna believe but my gut says slow down",
  "is support an actual person or a bot",
  "showed my brother and he said run lol",
  "still waiting on my first payout, day 3 now",
  "what proof do we have this is real",
  "im in for the small amount, thats my limit",
  "do withdrawals get delayed on weekends",
  "the whole thing gives me mixed feelings",
  "how much have you actually pulled out so far",
  "app froze mid transaction, anyone else",
  "not fully trusting it yet but watching",
  "why is the interface so confusing lol",
  "genuinely asking is this sustainable",
  "put in 100, gonna see what happens",
  "anyone else get cold feet after depositing",
  "how do i even verify my account is real",
  "the yield seems detached from reality ngl",
  "im cautious by nature so bear with me",
  "did your withdrawal actually hit your bank",
  "starting slow, no reason to rush",
  "whats stopping them from just taking the deposits",
  "my balance dropped and idk why",
  "sounds nice but ive heard that before",
  "can someone explain the staking part simply",
  "keeping receipts of everything just in case",
  "do we actually know who runs this",
  "waiting on a payout thats 2 days late now",
  "not convinced yet but not out either",
  "how long you been in and hows it going",
  "the referral thing feels a bit pyramid-y ngl",
  "only risking what i can shrug off",
  "does the app have 2fa or nah",
  "curious but keeping my guard up",
  "why cant i find reviews outside this chat",
  "tested small, still deciding",
  "anyone had trouble getting support to reply",
  "my deposit shows but not my earnings",
  "i just wanna see one real withdrawal proof",
  "playing it safe with a tiny amount",
  "is there a lockup period nobody mentioned",
  "feels early to trust it fully",
  "anyone else confused by the fees",
  "still nervous tbh, first time doing this",
  "how do i actually cash out to my bank",
  "went in with grocery money not rent money lol",
  "numbers are pretty but can i touch them",
  "waiting for a payout before i tell anyone",
  "why does it say error when i try to withdraw",
  "skeptical but the community keeps me watching",
  "does anyone actually get paid on time here",
  "keeping it low key till i see results",
  "whats the risk if crypto tanks",
  "my earnings paused and no explanation",
  "not putting my life savings in some app lol",
  "anyone verify the withdrawal actually clears",
  "im here but with heavy skepticism",
  "how do we know the balance isnt fake",
  "started tiny, watching before adding more",
  "is the real estate part actual property or just a name",
  "my payout button is greyed out, why",
  "cautious, been burned before honestly",
  "do they take a cut of your earnings",
  "waiting and watching, thats my whole strategy",
  "why is everyone so hyped, makes me more careful",
  "anyone got a payout over a grand yet",
  "small stake only for now",
  "genuinely unsure if i should add more",
  "does support ever actually reply",
  "my balance says one thing app says another",
  "keeping my deposit modest till i trust it",
  "how long before i can withdraw the first time",
  "not sold yet but keeping an eye out",
  "anyone else double checking everything twice",
  "whats the min to start?",
  "how long till first payout",
  "is it usdt only or",
  "do referrals stack lol",
  "wheres the staking option",
  "yo how do i actually deposit",
  "can i start with like $50",
  "wait can i use card or crypto only",
  "how many days for withdrawal to hit",
  "is there a lock in period",
  "do i need kyc for this??",
  "how do referrals work exactly",
  "can i withdraw anytime or nah",
  "where do i find my wallet address",
  "is 100 usdt enough to start",
  "payouts daily or weekly?",
  "how do i verify my account",
  "anyone know the min deposit rn",
  "trc20 or only erc20?",
  "do i earn while its locked",
  "wheres the reinvest option",
  "fee on withdrawals?",
  "how do i join the real estate one",
  "can someone explain the tiers",
  "new here whats step 1",
  "do i get a referral link somewhere",
  "how long b4 i see returns",
  "is the min different per plan",
  "what network for usdt",
  "can i deposit from binance directly",
  "how many refs to unlock next level",
  "where do i check my earnings",
  "how do i actually start staking",
  "can i cancel a stake early",
  "do i get charged if i pull out early",
  "how do payouts get sent to me",
  "whats the withdrawal minimum",
  "how do i add funds",
  "is there an app or just web",
  "how long does verification take",
  "what happens after i deposit",
  "where do i see my referral count",
  "can i change my plan later",
  "is payout automatic or do i claim",
  "min to start is what again",
  "how do i find my deposit address",
  "is kyc mandatory or nah",
  "can i put in more later or one time only",
  "whats the earliest i can withdraw",
  "do i need a minimum to withdraw",
  "where do i see pending payouts",
  "can i use metamask here",
  "how long is the staking cycle",
  "do i get paid in usdt too",
  "how do i level up my account",
  "is there a max deposit",
  "can i start small and add later",
  "how do i claim my first payout",
  "payout include principal or just profit?",
  "deposit fee if any?",
  "how do i connect a wallet",
  "is real estate separate from crypto here",
  "do i need id to withdraw",
  "how many days is the lock",
  "whats the min for the top tier",
  "can i refer without depositing first",
  "where do i toggle auto reinvest",
  "is payout every 24h or",
  "can i deposit bnb",
  "do i earn from my referrals deposits",
  "where do i put my deposit",
  "how long till account is active",
  "signup bonus or nah",
  "whats the smallest stake allowed",
  "can i withdraw partial or full only",
  "do i need to stake before referring",
  "can someone show me where staking is",
  "is min 10 or 100 im confused",
  "how do i get my referral code",
  "do withdrawals take a fee out",
  "how many levels of referral are there",
  "wheres the deposit button lol",
  "can i fund with a debit card",
  "daily withdrawal limit?",
  "whats the process after i sign up",
  "can i have multiple stakes at once",
  "how do i qualify for referral rewards",
  "is the min in usdt or dollars",
  "do payouts hit on weekends",
  "can i start today and withdraw next week",
  "how do i actually pick a plan",
  "welcome in 🤝",
  "yo welcome",
  "hey some new faces today",
  "we all started somewhere fr",
  "ask away, someone usually answers",
  "good to have you",
  "morning fam",
  "gm to everyone up early",
  "welcome aboard",
  "hey newcomers dont be shy",
  "glad you found this place",
  "settle in, grab a coffee",
  "no dumb questions here honestly",
  "welcome, ask whatever u need",
  "gn to the other side of the world lol",
  "afternoon all",
  "hope everyones doing ok today",
  "new here? just jump in",
  "hey welcome, decent crew in here",
  "morning legends",
  "yo whoever just joined, hi",
  "hey how long everyone been in here",
  "welcome, take your time",
  "hey folks",
  "morning from the uk",
  "gm from japan 🌏",
  "just say hi, we dont bite",
  "you'll get the hang of it quick",
  "welcome, im around if u have qs",
  "morning to the early birds",
  "glad ur here",
  "hey, first day?",
  "welcome welcome",
  "sup everyone",
  "nice to see fresh names in here",
  "come on in",
  "morning yall",
  "gm, how we feeling today",
  "everyone was new once",
  "hope u settle in fine",
  "hey there 🙌",
  "kinda chill in here most days lol",
  "morning, hope its a good one",
  "welcome, ppl here actually help tho",
  "hi all just checking in",
  "gm crew",
  "hey, welcome to the chaos",
  "dont stress, we all learn as we go",
  "morning, coffee first then charts",
  "welcome, glad u made it",
  "hey new person, wave back lol",
  "just breathe, ull figure it out",
  "morning morning",
  "yo gm everyone",
  "hi, jump in whenever",
  "welcome, no pressure",
  "morning, whats everyone up to",
  "welcome friend",
  "we started clueless too dont worry",
  "good afternoon peeps",
  "hi newcomers, ask away",
  "gm to the whole room",
  "hey stranger, come say hi",
  "morning ppl hope ur well",
  "welcome in, take a seat",
  "lot of new faces lately",
  "hi everyone hope todays good",
  "hey welcome, its chill here",
  "night shift crew say hi 😅",
  "morning, whats everyone up to today",
  "glad to see u here honestly",
  "hey new blood, welcome",
  "welcome, dont overthink it",
  "gm from down under",
  "hi hi, settle in",
  "morning fam how we doing",
  "yo new folks, welcome",
  "we all fumbled at first, its ok",
  "hey everyone gm",
  "hope ur morning is going ok",
  "hi, glad u joined",
  "come thru, welcome",
  "morning, good to see familiar names",
  "hey, dont be a stranger",
  "gm to anyone just waking up",
  "hi new here too, lets figure it out",
  "yo morning everyone hope ur good",
  "hey welcome",
  "we all remember day one lol",
  "hi folks, ask anything anytime",
  "morning, hope everyones good",
  "welcome, wave if ur new",
  "gm, lets have a good one",
  "hey there, glad u showed up",
  "welcome, no question too small honestly",
  "hi everyone, just saying hi",
  "hey new ppl, dont just lurk lol",
  "good to see you around",
  "morning, coffee then say hi",
  "hey, welcome from me 🤝",
  "welcome, ask us whatever",
];

// Templates that weave whatever topic the room is currently discussing.
// '{topic}' is replaced with the active topic at runtime.
export const HUMAN_TOPIC_TEMPLATES: string[] = [
  "anyone else watching {topic} rn?",
  "{topic} got me second guessing lol",
  "whats the play on {topic}",
  "still not sure about {topic} tbh",
  "{topic} everywhere today huh",
  "ok who keeps bringing up {topic} every 5 min",
  "someone explain {topic} to me like im 5",
  "{topic} lookin kinda shaky ngl",
  "yo is {topic} actually worth it or nah",
  "im in on {topic}, we'll see 🤞",
  "{topic} again? we literally talked about this yesterday",
  "not me refreshing {topic} every hour 😅",
  "{topic} feels overhyped imo",
  "waited 3 days on {topic} still nothing",
  "wait what happened with {topic}",
  "{topic} lowkey stressing me out",
  "{topic} could go either way rn",
  "{topic} confusing me on the app, where do i even click",
  "everyone chill about {topic} lol its not that deep",
  "so are we bullish on {topic} or",
  "{topic} been quiet lately",
  "bruh {topic} again i cant",
  "my cousin wont shut up about {topic}",
  "{topic} dipped and my heart dropped fr",
  "idk why but i trust {topic}",
  "anyone got a good breakdown on {topic}",
  "{topic} is all over my feed rn",
  "skeptical about {topic} but im listening",
  "{topic} or nah, someone convince me",
  "{topic} keeps me up at night lmao",
  "just read something wild about {topic}",
  "not touching {topic} till i understand it more",
  "whos actually made money off {topic}",
  "eh {topic} aint for me",
  "still holding {topic}, praying a lil",
  "does {topic} even make sense long term",
  "{topic} talk again, i need coffee for this",
  "kinda regret sleeping on {topic} earlier",
  "{topic} looking spicy today 👀",
  "someone dm me about {topic} im lost",
  "why is nobody talking about {topic}",
  "{topic} had a rough week huh",
  "half of yall dont even know what {topic} is lol",
  "thinking about jumping into {topic}, thoughts",
  "{topic} vibes are off today idk",
  "was gonna ignore {topic} but now im curious",
  "low on info about {topic}, anyone help",
  "man i missed the {topic} boat didnt i",
  "anyone else confused by the {topic} numbers",
  "gonna wait and see on {topic}",
  "{topic} either genius or a trap, no in between",
  "did {topic} move or is it just me",
];
